### ISSUE TITLE
Problem installing on Arch linux

### ISSUE THREAD

**Issue by alireza-amirsamimi** [eti0/arc-theme-orange#3]
Hello
I installed arc-theme successfully 
but i can't install arc-theme-orange on arch linux

`./autogen.sh --prefix=/usr
autoreconf: Entering directory`.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/bin/automake line 3936.
configure.ac:12: installing 'build-aux/install-sh'
configure.ac:12: installing 'build-aux/missing'
configure.ac:30: error: required file 'extra/Makefile.in' not found
Makefile.am:4: error: required directory ./extra does not exist
autoreconf: automake failed with exit status: 1
`

and another thing :)

I made some themes for docky based on your themes color.

https://github.com/alireza-amirsamimi/Arc-Dark-Docky-themes

docky is a dock program like plank and cairo and ...

You can fork my repository or add my repository link to your README file if you like!

thanks :)

**Comment by eti0** [comment]
Sorry about that, I'm not maintaining this repo anymore and when I created Arc-Orange loads of errors were made.

This should now be fixed.

I'll also add you Docky themes to the README.md for more visibility.
